CmsBundle\Entity\Artiste:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\ArtisteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
        image:
            type: string
            length: 255
            column: Image
        lien:
            type: string
            length: 255
            column: lien
            nullable: true
        date:
            type: datetime
        ajouterslider:
            type: boolean
        archive:
            type: boolean

    lifecycleCallbacks:
          prePersist: [ preUpload ]
          preUpdate: [ preUpload ]
          postPersist: [ upload ]
          postUpdate: [ upload ]
          postRemove: [ removeUpload ]

    manyToOne:
        categorie:
            targetEntity: CmsBundle\Entity\Categorie
            inversedBy: artiste
            joinColumn:
                nullable: false
        commercant1:
            targetEntity: CmsBundle\Entity\Commercant
            inversedBy: artiste
            joinColumn:
                nullable: true
        commercant2:
            targetEntity: CmsBundle\Entity\Commercant
            inversedBy: artiste
            joinColumn:
                nullable: true
        commercant3:
            targetEntity: CmsBundle\Entity\Commercant
            inversedBy: artiste
            joinColumn:
                nullable: true




