CmsBundle\Entity\Commercant:
    type: entity
    table: null
    repositoryClass: CmsBundle\Repository\CommercantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        image:
            type: string
            length: 255
            column: image
            nullable: true
        adresse:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        code:
            type: integer
        ville:
            type: string
            length: 255
        lat:
            type: string
            length: 255
        lng:
            type: string
            length: 255
        lien:
            type: string
            lenght: 255
            nullable: true

    oneToMany:
        commercant1:
            targetEntity: CmsBundle\Entity\Artiste
            mappedBy: commercant1
        commercant2:
            targetEntity: CmsBundle\Entity\Artiste
            mappedBy: commercant2
        commercant3:
            targetEntity: CmsBundle\Entity\Artiste
            mappedBy: commercant3

    lifecycleCallbacks:
          prePersist: [ preUpload ]
          preUpdate: [ preUpload, setUpdatedAtValue ]
          postPersist: [ upload ]
          postUpdate: [ upload ]
          postRemove: [ removeUpload ]
