<?php

namespace MobileBundle\Repository;

/**
 * MobileListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileListRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCommercantArtisteCategorie(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.id', 'a.dateDebut', 'a.dateFin')
            ->join('a.commercants', 'i')
            ->addSelect('i.nom', 'i.adresse', 'i.code', 'i.ville', 'i.lat', 'i.lng')
            ->join('a.artistess', 'v')
            ->addSelect('v.nom', 'v.date');
        return $qb->getQuery()->getResult();
    }

}
