<?php

namespace MobileBundle\Repository;
use CmsBundle\Entity\Artiste;


/**
 * MobileListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileListRepository extends \Doctrine\ORM\EntityRepository
{

    public function getArtistesFalse(){
//        Alias 's' = class searchrepository
//        Alias 'c' = categorie

        $qb = $this->createQueryBuilder('p')
            ->select('p.id', 'p.dateDebut', 'p.dateFin')
            ->join ('p.artistess', 'a')
            ->select ('a.id', 'a.nom', 'a.archive')
            ->where('a.archive = false')
            ->orderBy('a.nom', 'DESC')
            ->join ('p.commercants', 'c')
            ->select ('c.id', 'c.nom')
            ->orderBy('c.nom', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function getjsonArtistesFalse($date){
//        Alias 'p' = class mobileList
//        Alias 'ca' = categorie
//        Alias 'co' = commercants
//        Alias 'a' = artistess

        $qb = $this->createQueryBuilder('p')
            ->select('p.id', 'p.dateDebut', 'p.dateFin')
            ->Where ('p.dateDebut >= :dateNow')
            ->setParameter('dateNow', $date)
            ->join ('p.artistess', 'i')
            ->addSelect('i.nom', 'i.archive')
            ->where ('i.archive = false')
            ->orderBy ('i.nom', 'DESC')
            ->join ('i.categorie', 'ca')
            ->addSelect ('ca.nomDeLaCategorie')
            ->join ('p.commercants', 'co')
            ->addSelect ('co.nom as nomco', 'co.adresse', 'co.code', 'co.ville', 'co.lat', 'co.lng');

        return $qb->getQuery()->getResult();
    }

}
