<?php

namespace CmsBundle\Repository;

/**
 * AproposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AproposRepository extends \Doctrine\ORM\EntityRepository
{
}
