<?php

namespace CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommercantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercantRepository extends EntityRepository
{
}
