<?php

namespace CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresseRepository extends EntityRepository
{
    public function getIdItemPresse()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT MAX(a.item_id) FROM CmsBundle:Presse a'
            )
            ->getResult();
    }
}
