<?php

namespace CmsBundle\Repository;

/**
 * YoutubeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeRepository extends \Doctrine\ORM\EntityRepository
{
}
