#mobilelist_index:
#    path:     /
#    defaults: { _controller: "MobileBundle:MobileList:index" }
#    methods:  GET

mobilelist_indexByArtistes:
    path:     /
    defaults: { _controller: "MobileBundle:Artiste:indexByArtistes" }
    methods:  GET

mobilelist_show:
    path:     /{id}/show
    defaults: { _controller: "MobileBundle:MobileList:show" }
    methods:  GET

mobilelist_new:
    path:     /new
    defaults: { _controller: "MobileBundle:MobileList:new" }
    methods:  [GET, POST]

#mobilelist_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "MobileBundle:MobileList:edit" }
#    methods:  [GET, POST]

mobilelist_edit:
    path:     /{id}/edit
    defaults: { _controller: "MobileBundle:Artiste:edit" }
    methods:  [GET, POST]

mobilelist_delete:
    path:     /{id}/delete
    defaults: { _controller: "MobileBundle:MobileList:delete" }
    methods:  DELETE

###########################################
#############@   Routes Json  #############
###########################################
#
#mobile_index:
#    path:     /mobile_json
#    defaults: { _controller: "MobileBundle:Default:home" }
#    methods:  GET